### ISSUE TITLE
xcode14 不支持此库 

### ISSUE THREAD

**Issue by ActionsLjx** [zgjff/JJCarouselView#1]
Stored properties cannot be marked potentially unavailable with '@available'

 @available(iOS 13.0, *)
        internal lazy var _onTapPublisher = PassthroughSubject<(Cell, Object, Int), Never>()

**Comment by zgjff** [comment]
已修复此问题。。。暂时去除Combine支持。因为swift5.7不支持@available
![image](https://user-images.githubusercontent.com/20295066/196575650-81f5a223-0044-4b6b-add6-78c8e77b5d6e.png)
